connector:
  name: harness_gitconnector
  identifier: harnessgitconnector
  description: ""
  orgIdentifier: default
  projectIdentifier: Venkat_Devops
  type: Github
  spec:
    url: https://github.com/GITHUB_USERNAME/smartdevops-pipeline.git
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: GITHUB_USERNAME
          tokenRef: harness_gitpat
    apiAccess:
      type: Token
      spec:
        tokenRef: harness_gitpat
    executeOnDelegate: false
    type: Repo
