service:
  name: harness_flaskapp
  identifier: harnessflaskapp
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
      - manifest:
          identifier: flaskapp
          type: K8sManifest
          spec:
            store:
              type: Github
              spec:
                connectorRef: gitflaskappconnector
                gitFetchType: Branch
                paths:
                - guestbook/flaskapp-deployment.yaml
                - guestbook/flaskapp-svc.yaml
                repoName: smartdevops-pipeline
                branch: main
              skipResourceVersioning: false
              enableDeclarativeRollback: false
  gitOpsEnabled: false
